# Generated by Django 2.2.13 on 2021-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20210412_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='salary',
            field=models.CharField(default='00,000.00', max_length=16),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
