# Generated by Django 2.2.13 on 2021-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20210415_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='phoneNumber',
            field=models.IntegerField(default=None),
        ),
    ]
