# Generated by Django 2.2.13 on 2021-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210415_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='leave',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='phoneNumber',
            field=models.BigIntegerField(default=None),
        ),
    ]
