# Generated by Django 2.2.13 on 2021-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210416_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('Type', models.CharField(choices=[('complain', 'COMPLAIN'), ('suggestion', 'SUGGESTION')], default=None, max_length=10)),
                ('complain_text', models.TextField(max_length=50)),
            ],
        ),
    ]
