# Generated by Django 2.2.13 on 2021-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20210417_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='fullname',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
