# Generated by Django 2.2.13 on 2021-04-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_leave_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='fullname',
            new_name='Name',
        ),
    ]
