# Generated by Django 2.2.13 on 2021-04-16 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_remove_leave_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='leave',
        ),
        migrations.AddField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MainApp.employeeDetails'),
        ),
    ]
