# Generated by Django 2.2.13 on 2021-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_auto_20210417_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='leave',
            field=models.BigIntegerField(default=0),
        ),
    ]
